
public class FigmaScreenNames
{

    // Automatically generated by UnityFigmaBridge

    public const string MAIN_MENU = "Main Menu";
    public const string SUCCESS_REGIATRATION = "Success Regiatration";
    public const string REGISTRATION = "Registration";
    public const string SUCCESS_FORGOT_PASSWORD = "Success Forgot Password";
    public const string SUCCESSFULLY = "Successfully";
    public const string FORGOT_PASSWORD = "Forgot Password";
    public const string LOGIN = "Login";

}
